name = "profilweb-bestq-groups"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
[[d1_databases]]
binding = "DB"
database_name = "bestq-db"
database_id = "1ce5a99c-a839-4e1b-a915-55a36ddf5d3d"
migrations_dir = "src/db/migrations"
