name = "profilweb-bestq-groups"
compatibility_date = "2024-03-20"
account_id = "f8443625e4d94f28ebba9d1544c6865f"
[[d1_databases]]
binding = "DB"
database_name = "bestq-db"
database_id = "1ce5a99c-a839-4e1b-a915-55a36ddf5d3d"
migrations_dir = "src/db/migrations"
